language: scala
sudo: false
jdk: oraclejdk8
scala: 2.12.6

notifications:
  email:
    on_success: never
    on_failure: never

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt clean coverage test coverageReport

after_success:
  - sbt coveralls
